replicaCount: 3
springProfile: prod

parserSettings:
  jitterMin: 50
  jitterMax: 500
  failRate: 0.1

image:
  repository: feeham/crawler-parser
  tag: "latest"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: true
  host: parser.external.public.url

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 300m
    memory: 512Mi

probes:
  liveness:
    enabled: false
    path: /health
    port: 8080
    initialDelaySeconds: 5
    periodSeconds: 10
  readiness:
    enabled: false
    path: /ready
    port: 8080
    initialDelaySeconds: 2
    periodSeconds: 5

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50
