apiVersion: v1
kind: Namespace
metadata:
  name: crawler-infrastructure
---
apiVersion: v1
kind: Namespace
metadata:
  name: crawler-apps
---
apiVersion: v1
kind: Namespace
metadata:
  name: crawler-external

