
apiVersion: v1
kind: Service
metadata:
  name: crawler-pg-db
  labels:
    app: crawler-pg-db
spec:
  ports:
  - port: {{ .Values.postgres.port }}
    targetPort: {{ .Values.postgres.port }}
    name: postgres
  selector:
    app: crawler-pg-db
  type: ClusterIP

