
apiVersion: v1
kind: Service
metadata:
  name: crawler-zookeeper
  labels:
    app: crawler-zookeeper
spec:
  ports:
  - port: {{ .Values.zookeeper.port }}
    targetPort: {{ .Values.zookeeper.port }}
    name: client
  selector:
    app: crawler-zookeeper
  type: ClusterIP

