
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: crawler-kafkadrop
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: {{ .Values.kafkadrop.ingress.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: crawler-kafkadrop
                port:
                  number: {{ .Values.kafkadrop.port }}

