
apiVersion: v1
kind: Service
metadata:
  name: crawler-kafkadrop
  labels:
    app: crawler-kafkadrop
spec:
  ports:
  - port: {{ .Values.kafkadrop.port }}
    targetPort: {{ .Values.kafkadrop.port }}
    name: http
  selector:
    app: crawler-kafkadrop
  type: ClusterIP

